repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: "v4.5.0"
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: check-json
      - id: check-xml
      - id: check-yaml
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.0
    hooks:
      - id: python-safety-dependencies-check
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.3
    hooks:
      - id: python-bandit-vulnerability-check
  - repo: local
    hooks:
      - id: py.test
        name: py.test
        language: system
        entry: sh -c 'TEST_SKIP_CAPPED=1 py.test'
        files: ""
